"""Create table industry_trends_jobs

Revision ID: be6ae4a89ed8
Revises: b2034c94bede
Create Date: 2025-07-08 09:55:02.899375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6ae4a89ed8'
down_revision: Union[str, None] = 'b2034c94bede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_trends_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Double(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('tickers', sa.String(), nullable=False),
    sa.Column('up_period', sa.Integer(), nullable=False),
    sa.Column('down_period', sa.Integer(), nullable=False),
    sa.Column('vol_window', sa.Integer(), nullable=False),
    sa.Column('max_leverage', sa.Double(), nullable=False),
    sa.Column('target_volatility', sa.Double(), nullable=False),
    sa.Column('trade_cost_per_share', sa.Double(), nullable=False),
    sa.Column('trade_cost_min', sa.Double(), nullable=False),
    sa.Column('rebalance_threshold', sa.Double(), nullable=False),
    sa.Column('user', sa.String(), server_default='*', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry_trends_jobs')
    # ### end Alembic commands ###
