"""Add user to jobs

Revision ID: b2034c94bede
Revises: 60f50e982c8b
Create Date: 2025-06-17 12:15:11.565223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2034c94bede'
down_revision: Union[str, None] = '60f50e982c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user', sa.String(), server_default='*', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'user')
    # ### end Alembic commands ###
