"""Add exclude_prev_month to dm jobs

Revision ID: d038dd583b41
Revises: 4816e5524d4d
Create Date: 2025-07-15 14:54:36.682107

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd038dd583b41'
down_revision: Union[str, None] = '4816e5524d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('exclude_prev_month', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'exclude_prev_month')
    # ### end Alembic commands ###
