"""Add max_assets to jobs

Revision ID: 4816e5524d4d
Revises: 85f6891d4807
Create Date: 2025-07-11 16:25:22.555444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4816e5524d4d'
down_revision: Union[str, None] = '85f6891d4807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('max_assets', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_assets')
    # ### end Alembic commands ###
