"""it cagr & drawdown

Revision ID: bdf9eed751b4
Revises: 380f13ba0602
Create Date: 2025-09-16 16:27:35.868895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf9eed751b4'
down_revision: Union[str, None] = '380f13ba0602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry_trends_jobs', sa.Column('cagr', sa.Double(), server_default='0.0', nullable=False))
    op.add_column('industry_trends_jobs', sa.Column('drawdown', sa.Double(), server_default='0.0', nullable=False))
    op.add_column('industry_trends_jobs', sa.Column('cagr_benchmark', sa.Double(), server_default='0.0', nullable=False))
    op.add_column('industry_trends_jobs', sa.Column('drawdown_benchmark', sa.Double(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry_trends_jobs', 'drawdown_benchmark')
    op.drop_column('industry_trends_jobs', 'cagr_benchmark')
    op.drop_column('industry_trends_jobs', 'drawdown')
    op.drop_column('industry_trends_jobs', 'cagr')
    # ### end Alembic commands ###
