"""Add rebalance_threshold to job

Revision ID: 85d504531d53
Revises: d038dd583b41
Create Date: 2025-08-08 09:10:05.060800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d504531d53'
down_revision: Union[str, None] = 'd038dd583b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('rebalance_threshold', sa.Double(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'rebalance_threshold')
    # ### end Alembic commands ###
