"""dm cagr & drawdown

Revision ID: 380f13ba0602
Revises: 85d504531d53
Create Date: 2025-09-16 10:29:01.768873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380f13ba0602'
down_revision: Union[str, None] = '85d504531d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cagr', sa.Double(), server_default='0.0', nullable=False))
    op.add_column('jobs', sa.Column('drawdown', sa.Double(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'drawdown')
    op.drop_column('jobs', 'cagr')
    # ### end Alembic commands ###
